# Generated by Django 3.2.5 on 2021-08-02 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_auto_20210802_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='bedrooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=144, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(),
        ),
    ]
